# Generated by Django 2.0.7 on 2018-07-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_auto_20180718_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
        migrations.AlterField(
            model_name='word',
            name='adder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
