# Generated by Django 2.0.7 on 2018-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_auto_20180721_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
