# Generated by Django 2.0.7 on 2018-07-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('definitions', '0004_dislike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='adder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions.Word'),
        ),
    ]
