# Generated by Django 2.0.7 on 2018-10-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0005_auto_20180719_0445'),
        ('definitions', '0003_definition_updated_at'),
    ]

    operations = [
    ]
