# Generated by Django 2.0.7 on 2018-10-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_merge_20181002_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='definition',
            name='antonyms',
            field=models.ManyToManyField(related_name='antonyms', to='definitions.Word'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='synonyms',
            field=models.ManyToManyField(related_name='synonyms', to='definitions.Word'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='tags',
            field=models.ManyToManyField(to='definitions.Tag'),
        ),
    ]
